defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

display:
  image_size: 800
  gating_display_stretch: 1
  lview_display_stretch: 1
  windowing_sensitivity: 0.03  # 1 for default, below 1 for slower, above 1 for faster
  n_interactive_points: 10
  n_points_contour: 500  # ideally choose a multiple of 100 (for calculation of closest points)
  contour_thickness: 3
  point_thickness: 1
  point_radius: 10

gating:
  normalize_step: 100
  intramural_threshold: 1.5  # elliptic ratio threshold to define intramural part of vessel
  
  # butterworth filter for gating
  lowcut: 0.6667  # lowcut frequency for Butterworth filter
  highcut: 3.0  # highcut frequency for Butterworth filter
  order: 6  # order of Butterworth filter

  # identify extrema
  min_height_percentile: 50  # percentile of how much higher next peak has to be (y-component)
  min_distance: 12  # minimum distance between peaks (x-component)

  # automatic gating threshold for frame difference of extrema of the two signals
  auto_gating_threshold: 5

  both_extrema: True  # set to True to use both extrema (contour- and image-based) for gating

report:
  plot: False
  save_as_csv: False

save:
  autosave_interval: 10000  # in ms
  use_xml_files: False  # set True to use .xml files instead of .json to save contours, etc.
  # nifti_dir: '/home/sebalzer/Documents/Projects/AAOCASeg/niftis'
  nifti_dir: '/home/yungselm/Documents/niftis'
  save_niftis: 'none'  # 'contoured', 'all', 'none' (which frames to save as NIfTi)
  save_2d: False
  save_3d: True

segmentation:
  # model_file: '/home/sebalzer/Documents/Projects/AAOCASeg/models/u2net_2d_MINMAX_512_best.h5'
  model_file: '/home/yungselm/Documents/IVUS_models/u2net_2d_MINMAX_512_best.h5'
  input_dir: /home/sebalzer/Documents/Projects/AAOCASeg/IVUSimages  # only needed for segment_files.py
  batch_size: 16
  conserve_memory: True  # set to True for devices with less than 32 GB RAM (increases inference times)

filters:
  plot: True
  nonlocal_means: 
    patch_size: 2
    patch_distance: 2
    h: 1
    fast_mode: True
    sigma: 0.0
    preserve_range: False